png("plot3.png")
plot(data$Sub_metering_1, type="l", xaxt = "n", main="", ylab="Energy sub metering")
lines(data$Sub_metering_2, col = "red")
lines(data$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), col=c("black", "red", "blue"))
at <- seq(1, length(data[,2]) + 1, by = 24 * 60)
labels <- seq(from = data[at[1],2], by = "day", length.out = length(at))
axis(side = 1, at = at, labels = format(labels, format = "%a"))
dev.off()
